a = int(4)
b = int (5.66)
c = int ("45")
print ("a = ", a)
print ("b = ", b)
print ("c = ", c)

d = float (6)
e = float (6.544)
f = float ("655")
print ("d = ", d)
print ("e = ", e)
print ("f = ", f)

g = str (65)
h = str ("tr56")
i = str (76.433)
print ("g = ", g)
print ("h = ", h)
print ("i = ", i)